# Generated by Django 6.0.7 on 2026-07-11 15:55

import apps.annotator.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnatomyCase',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('case_type', models.CharField(choices=[('BRAIN', 'Brain'), ('HEAD_AND_NECK', 'Head And Neck'), ('SPINE', 'Spine'), ('CHEST', 'Chest'), ('ABDOMEN_AND_PELVIS', 'Abdomen And Pelvis'), ('UPPER_LIMB', 'Upper Limb'), ('LOWER_LIMB', 'Lower Limb')], max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Anatomy Case',
                'verbose_name_plural': 'Anatomy Cases',
                'indexes': [models.Index(fields=['slug'], name='annotator_a_slug_64f6f2_idx')],
            },
        ),
        migrations.CreateModel(
            name='AnatomyImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(height_field='image_height', upload_to=apps.annotator.models.ImageUploadPath('anatomy_images'), validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], width_field='image_width')),
                ('image_height', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('image_width', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='annotator.anatomycase')),
            ],
            options={
                'verbose_name': 'Anatomy Image',
                'verbose_name_plural': 'Anatomy Images',
            },
        ),
        migrations.CreateModel(
            name='AnnotatedImage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(height_field='image_height', upload_to=apps.annotator.models.ImageUploadPath('annotated_images'), validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], width_field='image_width')),
                ('image_height', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('image_width', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotated_images', to='annotator.anatomycase')),
            ],
            options={
                'verbose_name': 'Annotated Image',
                'verbose_name_plural': 'Annotated Images',
            },
        ),
    ]
