# Generated by Django 6.0.7 on 2026-07-12 09:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnatomyCaseType',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=150, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Anatomy Case Type',
                'verbose_name_plural': 'Anatomy Case Types',
                'indexes': [models.Index(fields=['id'], name='annotator_a_id_d283e2_idx'), models.Index(fields=['slug'], name='annotator_a_slug_e08f28_idx')],
                'constraints': [models.UniqueConstraint(fields=('title',), name='uniq_title')],
            },
        ),
        migrations.AlterField(
            model_name='anatomycase',
            name='case_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='annotator.anatomycasetype'),
        ),
    ]
