# Generated by Django 6.0.7 on 2026-07-12 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0002_anatomycasetype_alter_anatomycase_case_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anatomycase',
            name='case_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='annotator.anatomycasetype'),
        ),
    ]
