# Generated by Django 6.0.7 on 2026-07-13 10:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0003_alter_anatomycase_case_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('class_label', models.CharField(choices=[('TUMOR', 'Tumor'), ('EDIMA', 'Edima'), ('NECROSIS', 'Necrosis'), ('OTHER', 'Other')], max_length=100)),
                ('annotated_color', models.CharField(max_length=20)),
                ('points', models.JSONField()),
                ('is_closed', models.BooleanField(default=False)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='annotator.anatomyimage')),
            ],
            options={
                'verbose_name': 'Annotation',
                'verbose_name_plural': 'Annotations',
            },
        ),
        migrations.DeleteModel(
            name='AnnotatedImage',
        ),
        migrations.AddIndex(
            model_name='annotation',
            index=models.Index(fields=['image'], name='annotator_a_image_i_39894f_idx'),
        ),
        migrations.AddIndex(
            model_name='annotation',
            index=models.Index(fields=['class_label'], name='annotator_a_class_l_2ebf8b_idx'),
        ),
    ]
