# Generated by Django 6.0.7 on 2026-07-09 16:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=20)),
                ('value', models.SlugField(blank=True, editable=False, unique=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'indexes': [models.Index(fields=['id'], name='kanaban_tag_id_a22d0f_idx'), models.Index(fields=['value'], name='kanaban_tag_value_ac4aa2_idx')],
                'constraints': [models.UniqueConstraint(fields=('label',), name='uniq_tag_label'), models.UniqueConstraint(fields=('value',), name='uniq_tag_value')],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('priority', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], max_length=20)),
                ('due_date', models.DateTimeField()),
                ('tags', models.ManyToManyField(related_name='tasks', to='kanaban.tag')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['id'], name='kanaban_tas_id_ae61fb_idx'), models.Index(fields=['due_date'], name='kanaban_tas_due_dat_a5b690_idx')],
                'constraints': [models.UniqueConstraint(fields=('title',), name='uniq_task_title')],
            },
        ),
    ]
